CREATE TABLE BOLDRS_EmailActivityLog (
     Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     Event VARCHAR2(255) NOT NULL,
     RecipientEmail VARCHAR2(255) NOT NULL,
     SenderEmail VARCHAR2(255) NOT NULL,
     MailSubject VARCHAR2(255) NOT NULL,
     MailBody CLOB NULL,
     CreatedDate TIMESTAMP NOT NULL,
     ModifiedDate TIMESTAMP NULL,
     InitiatedBy NUMBER NOT NULL,
     UserId NUMBER NULL,
     GroupId NUMBER NULL,
     ItemId RAW(16) NULL, -- UUID equivalent
     CommentId NUMBER NULL,
     PermissionId NUMBER NULL,
     Status NUMBER NOT NULL,
     StatusMessage CLOB NULL,
     IsActive NUMBER(1) NOT NULL
);

ALTER TABLE BOLDRS_EmailActivityLog ADD CONSTRAINT fk_emailactivitylog_user FOREIGN KEY (UserId) REFERENCES BOLDRS_User(Id);

ALTER TABLE BOLDRS_EmailActivityLog ADD CONSTRAINT fk_emailactivitylog_group FOREIGN KEY (GroupId) REFERENCES BOLDRS_Group(Id);

ALTER TABLE BOLDRS_EmailActivityLog ADD CONSTRAINT fk_emailactivitylog_item FOREIGN KEY (ItemId) REFERENCES BOLDRS_Item(Id);

ALTER TABLE BOLDRS_EmailActivityLog ADD CONSTRAINT fk_emailactivitylog_comment FOREIGN KEY (CommentId) REFERENCES BOLDRS_Comment(Id);

-- Add nullable SkipAttachment and SkipMail columns to support no-data options for existing installations
ALTER TABLE BOLDRS_ScheduleDetail ADD SkipAttachment NUMBER(1);
ALTER TABLE BOLDRS_ScheduleDetail ADD SkipMail NUMBER(1);
ALTER TABLE BOLDRS_ScheduleDetail  ADD ScheduleRunStatus VARCHAR2(1000) DEFAULT 'Idle' NOT NULL;

CREATE TABLE BOLDRS_ReportCopyLog (
    Id RAW(16) NOT NULL PRIMARY KEY,
    BatchId RAW(16) NULL,
    IsBulkCopy NUMBER(1) NOT NULL,
    SourceItemId RAW(16) NOT NULL,
    SourceItemName VARCHAR2(255) NOT NULL,
    SourceCategoryId RAW(16) NULL,
    SourceCategoryName VARCHAR2(255) NULL,
    SourceTenantId RAW(16) NOT NULL,
    CopySiteType VARCHAR2(255) NULL,
    ExternalSiteUrl VARCHAR2(255) NULL,
    DestinationTenantId RAW(16) NOT NULL,
    DestinationTenantName VARCHAR2(255) NOT NULL,
    DestinationCategoryPath VARCHAR2(1000) NOT NULL,
    DestinationCategoryId RAW(16) NULL,
    DestinationItemId RAW(16) NULL,
    DestinationItemName VARCHAR2(255) NOT NULL,
    IsOverwrite NUMBER(1) NOT NULL,
    CopiedByUserId NUMBER NOT NULL,
    CopiedAt TIMESTAMP NOT NULL,
    Status VARCHAR2(50) NOT NULL,
    FailureReason CLOB NULL
);

ALTER TABLE BOLDRS_ReportCopyLog ADD CONSTRAINT fk_reportcopylog_user FOREIGN KEY (CopiedByUserId) REFERENCES BOLDRS_User(Id);

ALTER TABLE BOLDRS_ReportCopyLog ADD CONSTRAINT fk_reportcopylog_item FOREIGN KEY (SourceItemId) REFERENCES BOLDRS_Item(Id);