CREATE TABLE BOLDRS_ItemSettings(
	Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ItemId  VARCHAR(36) NOT NULL,
    ItemConfig CLOB,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1,0) NOT NULL)
;

ALTER TABLE BOLDRS_ItemSettings ADD CONSTRAINT FK_ItemSettings_ItemId FOREIGN KEY(ItemId) REFERENCES BOLDRS_Item (Id)
;
CREATE TABLE BOLDRS_CustomEmailTemplate (
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    IsEnabled NUMBER(1,0) NULL,
    DisclaimerContent NVARCHAR2(255) NOT NULL,
    HeaderContent NVARCHAR2(255) NULL,
    Subject NVARCHAR2(255) NULL,
    TemplateName NVARCHAR2(255) NULL,
    MailBody NCLOB,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NULL,
    SendEmailAsHTML NUMBER(1,0) NOT NULL,
    CustomVisibilityOptions NCLOB NOT NULL,
    IsActive NUMBER(1,0) NOT NULL,
    TemplateId NUMBER NOT NULL,
    IsDefaultTemplate NUMBER(1,0) NOT NULL,
    IsSystemDefault NUMBER(1,0) NOT NULL,
    Description NVARCHAR2(255) NULL,
    ModifiedBy NUMBER NOT NULL
);