ALTER TABLE BOLDRS_ScheduleDetail ADD ReplytoEmail CLOB NULL
;

CREATE TABLE BOLDRS_MultiTabReport (
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ParentReportId VARCHAR2(36) NOT NULL,
    ChildReportId VARCHAR2(36) NOT NULL,
    OrderNumber NUMBER NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(5) NOT NULL,
    TabName VARCHAR2(255)
);


ALTER TABLE BOLDRS_MultiTabReport ADD CONSTRAINT fk_multitabreport_parentreportid FOREIGN KEY (ParentReportId) REFERENCES BOLDRS_Item (Id);

ALTER TABLE BOLDRS_MultiTabReport ADD CONSTRAINT fk_multitabreport_childreportid FOREIGN KEY (ChildReportId) REFERENCES BOLDRS_Item (Id);
