CREATE TABLE BOLDRS_EmailActivityLog (
     Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     Event VARCHAR2(255) NOT NULL,
     RecipientEmail VARCHAR2(255) NOT NULL,
     SenderEmail VARCHAR2(255) NOT NULL,
     MailSubject VARCHAR2(255) NOT NULL,
     MailBody CLOB NULL,
     CreatedDate TIMESTAMP NOT NULL,
     ModifiedDate TIMESTAMP NULL,
     InitiatedBy NUMBER NOT NULL,
     UserId NUMBER NULL,
     GroupId NUMBER NULL,
     ItemId RAW(16) NULL, -- UUID equivalent
     CommentId NUMBER NULL,
     PermissionId NUMBER NULL,
     Status NUMBER NOT NULL,
     StatusMessage CLOB NULL,
     IsActive NUMBER(1) NOT NULL
);

ALTER TABLE BOLDRS_EmailActivityLog ADD CONSTRAINT fk_emailactivitylog_user FOREIGN KEY (UserId) REFERENCES BOLDRS_User(Id);

ALTER TABLE BOLDRS_EmailActivityLog ADD CONSTRAINT fk_emailactivitylog_group FOREIGN KEY (GroupId) REFERENCES BOLDRS_Group(Id);

ALTER TABLE BOLDRS_EmailActivityLog ADD CONSTRAINT fk_emailactivitylog_item FOREIGN KEY (ItemId) REFERENCES BOLDRS_Item(Id);

ALTER TABLE BOLDRS_EmailActivityLog ADD CONSTRAINT fk_emailactivitylog_comment FOREIGN KEY (CommentId) REFERENCES BOLDRS_Comment(Id);

-- Add nullable SkipAttachment and SkipMail columns to support no-data options for existing installations
ALTER TABLE BOLDRS_ScheduleDetail ADD SkipAttachment NUMBER(1);
ALTER TABLE BOLDRS_ScheduleDetail ADD SkipMail NUMBER(1);
ALTER TABLE BOLDRS_ScheduleDetail  ADD ScheduleRunStatus VARCHAR2(1000) DEFAULT 'Idle' NOT NULL;
